//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace ATMMVC.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ATMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ATMEntities object using the connection string found in the 'ATMEntities' section of the application configuration file.
        /// </summary>
        public ATMEntities() : base("name=ATMEntities", "ATMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ATMEntities object.
        /// </summary>
        public ATMEntities(string connectionString) : base(connectionString, "ATMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ATMEntities object.
        /// </summary>
        public ATMEntities(EntityConnection connection) : base(connection, "ATMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<customer> customers
        {
            get
            {
                if ((_customers == null))
                {
                    _customers = base.CreateObjectSet<customer>("customers");
                }
                return _customers;
            }
        }
        private ObjectSet<customer> _customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<transaction> transactions
        {
            get
            {
                if ((_transactions == null))
                {
                    _transactions = base.CreateObjectSet<transaction>("transactions");
                }
                return _transactions;
            }
        }
        private ObjectSet<transaction> _transactions;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocustomers(customer customer)
        {
            base.AddObject("customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the transactions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotransactions(transaction transaction)
        {
            base.AddObject("transactions", transaction);
        }

        #endregion
    }
    #endregion
    
    #region Entities
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ATMModel", Name="customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new customer object.
        /// </summary>
        /// <param name="idCustomer">Initial value of the idCustomer property.</param>
        /// <param name="firstName">Initial value of the firstName property.</param>
        /// <param name="lastName">Initial value of the lastName property.</param>
        /// <param name="account">Initial value of the account property.</param>
        /// <param name="cDate">Initial value of the cDate property.</param>
        public static customer Createcustomer(global::System.String idCustomer, global::System.String firstName, global::System.String lastName, global::System.String account, global::System.String cDate)
        {
            customer customer = new customer();
            customer.idCustomer = idCustomer;
            customer.firstName = firstName;
            customer.lastName = lastName;
            customer.account = account;
            customer.cDate = cDate;
            return customer;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String idCustomer
        {
            get
            {
                return _idCustomer;
            }
            set
            {
                if (_idCustomer != value)
                {
                    OnidCustomerChanging(value);
                    ReportPropertyChanging("idCustomer");
                    _idCustomer = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("idCustomer");
                    OnidCustomerChanged();
                }
            }
        }
        private global::System.String _idCustomer;
        partial void OnidCustomerChanging(global::System.String value);
        partial void OnidCustomerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstName
        {
            get
            {
                return _firstName;
            }
            set
            {
                OnfirstNameChanging(value);
                ReportPropertyChanging("firstName");
                _firstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstName");
                OnfirstNameChanged();
            }
        }
        private global::System.String _firstName;
        partial void OnfirstNameChanging(global::System.String value);
        partial void OnfirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String lastName
        {
            get
            {
                return _lastName;
            }
            set
            {
                OnlastNameChanging(value);
                ReportPropertyChanging("lastName");
                _lastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("lastName");
                OnlastNameChanged();
            }
        }
        private global::System.String _lastName;
        partial void OnlastNameChanging(global::System.String value);
        partial void OnlastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String account
        {
            get
            {
                return _account;
            }
            set
            {
                OnaccountChanging(value);
                ReportPropertyChanging("account");
                _account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("account");
                OnaccountChanged();
            }
        }
        private global::System.String _account;
        partial void OnaccountChanging(global::System.String value);
        partial void OnaccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cDate
        {
            get
            {
                return _cDate;
            }
            set
            {
                OncDateChanging(value);
                ReportPropertyChanging("cDate");
                _cDate = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("cDate");
                OncDateChanged();
            }
        }
        private global::System.String _cDate;
        partial void OncDateChanging(global::System.String value);
        partial void OncDateChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ATMModel", Name="transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new transaction object.
        /// </summary>
        /// <param name="idTransaction">Initial value of the idTransaction property.</param>
        /// <param name="tStamp">Initial value of the tStamp property.</param>
        /// <param name="account">Initial value of the account property.</param>
        /// <param name="debit">Initial value of the debit property.</param>
        /// <param name="credit">Initial value of the credit property.</param>
        public static transaction Createtransaction(global::System.Int32 idTransaction, global::System.String tStamp, global::System.String account, global::System.Double debit, global::System.Double credit)
        {
            transaction transaction = new transaction();
            transaction.idTransaction = idTransaction;
            transaction.tStamp = tStamp;
            transaction.account = account;
            transaction.debit = debit;
            transaction.credit = credit;
            return transaction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTransaction
        {
            get
            {
                return _idTransaction;
            }
            set
            {
                if (_idTransaction != value)
                {
                    OnidTransactionChanging(value);
                    ReportPropertyChanging("idTransaction");
                    _idTransaction = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idTransaction");
                    OnidTransactionChanged();
                }
            }
        }
        private global::System.Int32 _idTransaction;
        partial void OnidTransactionChanging(global::System.Int32 value);
        partial void OnidTransactionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tStamp
        {
            get
            {
                return _tStamp;
            }
            set
            {
                OntStampChanging(value);
                ReportPropertyChanging("tStamp");
                _tStamp = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tStamp");
                OntStampChanged();
            }
        }
        private global::System.String _tStamp;
        partial void OntStampChanging(global::System.String value);
        partial void OntStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String account
        {
            get
            {
                return _account;
            }
            set
            {
                OnaccountChanging(value);
                ReportPropertyChanging("account");
                _account = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("account");
                OnaccountChanged();
            }
        }
        private global::System.String _account;
        partial void OnaccountChanging(global::System.String value);
        partial void OnaccountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double debit
        {
            get
            {
                return _debit;
            }
            set
            {
                OndebitChanging(value);
                ReportPropertyChanging("debit");
                _debit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("debit");
                OndebitChanged();
            }
        }
        private global::System.Double _debit;
        partial void OndebitChanging(global::System.Double value);
        partial void OndebitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double credit
        {
            get
            {
                return _credit;
            }
            set
            {
                OncreditChanging(value);
                ReportPropertyChanging("credit");
                _credit = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("credit");
                OncreditChanged();
            }
        }
        private global::System.Double _credit;
        partial void OncreditChanging(global::System.Double value);
        partial void OncreditChanged();

        #endregion
    
    }

    #endregion
    
}
