//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMWCFC.ATMWCFRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATMWCFRef.IATMWCFSvc")]
    public interface IATMWCFSvc {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IATMWCFSvc/Process", ReplyAction="http://tempuri.org/IATMWCFSvc/ProcessResponse")]
        string Process(string sMessage);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IATMWCFSvcChannel : ATMWCFC.ATMWCFRef.IATMWCFSvc, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMWCFSvcClient : System.ServiceModel.ClientBase<ATMWCFC.ATMWCFRef.IATMWCFSvc>, ATMWCFC.ATMWCFRef.IATMWCFSvc {
        
        public ATMWCFSvcClient() {
        }
        
        public ATMWCFSvcClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMWCFSvcClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMWCFSvcClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMWCFSvcClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Process(string sMessage) {
            return base.Channel.Process(sMessage);
        }
    }
}
