//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATMWebSvcC.ATMRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ATMRef.ATMSvcSoap")]
    public interface ATMSvcSoap {
        
        // CODEGEN: Generating message contract since element name sMessage from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Process", ReplyAction="*")]
        ATMWebSvcC.ATMRef.ProcessResponse Process(ATMWebSvcC.ATMRef.ProcessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Process", Namespace="http://tempuri.org/", Order=0)]
        public ATMWebSvcC.ATMRef.ProcessRequestBody Body;
        
        public ProcessRequest() {
        }
        
        public ProcessRequest(ATMWebSvcC.ATMRef.ProcessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sMessage;
        
        public ProcessRequestBody() {
        }
        
        public ProcessRequestBody(string sMessage) {
            this.sMessage = sMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProcessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ProcessResponse", Namespace="http://tempuri.org/", Order=0)]
        public ATMWebSvcC.ATMRef.ProcessResponseBody Body;
        
        public ProcessResponse() {
        }
        
        public ProcessResponse(ATMWebSvcC.ATMRef.ProcessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ProcessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ProcessResult;
        
        public ProcessResponseBody() {
        }
        
        public ProcessResponseBody(string ProcessResult) {
            this.ProcessResult = ProcessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ATMSvcSoapChannel : ATMWebSvcC.ATMRef.ATMSvcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ATMSvcSoapClient : System.ServiceModel.ClientBase<ATMWebSvcC.ATMRef.ATMSvcSoap>, ATMWebSvcC.ATMRef.ATMSvcSoap {
        
        public ATMSvcSoapClient() {
        }
        
        public ATMSvcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ATMSvcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMSvcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ATMSvcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ATMWebSvcC.ATMRef.ProcessResponse ATMWebSvcC.ATMRef.ATMSvcSoap.Process(ATMWebSvcC.ATMRef.ProcessRequest request) {
            return base.Channel.Process(request);
        }
        
        public string Process(string sMessage) {
            ATMWebSvcC.ATMRef.ProcessRequest inValue = new ATMWebSvcC.ATMRef.ProcessRequest();
            inValue.Body = new ATMWebSvcC.ATMRef.ProcessRequestBody();
            inValue.Body.sMessage = sMessage;
            ATMWebSvcC.ATMRef.ProcessResponse retVal = ((ATMWebSvcC.ATMRef.ATMSvcSoap)(this)).Process(inValue);
            return retVal.Body.ProcessResult;
        }
    }
}
